import random

def joke():
    jokes = [
        "Why don't scientists trust atoms? Because they make up everything!",
        "I told my wife she should embrace her mistakes. She gave me a hug.",
        "What did the janitor say when he jumped out of the closet? Supplies!",
        "Parallel lines have so much in common. It’s a shame they'll never meet.",
        "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
        "Why don't skeletons fight each other? They don't have the guts.",
        "Did you hear about the mathematician who’s afraid of negative numbers? He will stop at nothing to avoid them.",
        "I only know 25 letters of the alphabet. I don't know y.",
        "What do you call fake spaghetti? An impasta.",
        "Why don't scientists trust genetics? Because it's all in your genes.",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "Why don’t oysters donate to charity? Because they are shellfish.",
        "I told my wife she was drawing her eyebrows too high. She looked surprised.",
        "Why did the scarecrow become a successful motivational speaker? Because he was outstanding in his field!",
        "Why did the JavaScript developer go broke? Because he lost his `$.change`.",
        "Why did the coffee file a police report? It got mugged.",
        "Why do programmers prefer dark mode? Light attracts bugs.",
        "What did one ocean say to the other ocean? Nothing, they just waved.",
        "I used to play piano by ear, but now I use my hands and fingers.",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did one hat say to the other? Stay here, I'm going on ahead!",
        "Why don't skeletons fight each other? They don't have the guts.",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "Why did the scarecrow become a successful motivational speaker? Because he was outstanding in his field!",
        "Why did the JavaScript developer go broke? Because he lost his `$.change`.",
        "Why did the coffee file a police report? It got mugged.",
        "Why do programmers prefer dark mode? Light attracts bugs.",
        "What did one ocean say to the other ocean? Nothing, they just waved.",
        "I used to play piano by ear, but now I use my hands and fingers.",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did one hat say to the other? Stay here, I'm going on ahead!",
        "Did you hear about the restaurant on the moon? Great food, but no atmosphere.",
        "What do you call a fish with no eyes? Fsh!",
        "What do you call a lazy kangaroo? Pouch potato.",
        "I'm on a seafood diet. I see food, and I eat it.",
        "Why did the scarecrow win an award? Because he was outstanding in his field.",
        "I used to be indecisive, but now I'm not so sure.",
        "My therapist told me the best way to deal with existential dread is to just accept that I'm insignificant. I feel so much better now.",
        "My body is a temple. A really messy, unorganized temple with questionable plumbing.",
        "I'm not lazy, I'm just highly motivated to do nothing.",
        "Coffee: the reason I wake up in the morning. And the reason I need to go back to bed.",
        "I'm not sure what's wrong with me. I can't stop singing songs from the 90s, even if I don't know the words.",
        "My dating profile should just say: 'Comes with free anxiety and occasional existential dread.'",
        "I'm so bad at multitasking that I can barely sing one song at a time.",
        "I'm the kind of person who forgets what they came into a room for halfway through.",
        "My spirit animal is a sloth with a caffeine addiction.",
        "The only thing worse than having no internet is having slow internet.",
        "Adulting is basically just googling how to do things you should already know.",
        "The older I get, the more I understand why old people yell at clouds.",
        "Sleep is my superpower. I can turn off my brain for like, eight hours straight.",
        "I'm not saying I'm Batman, but I do own a lot of black clothes and have a crippling fear of bats.",
        "My Hogwarts sorting hat is still deciding between Gryffindor and the snack table.",
        "I'm not sure what's more unrealistic, a talking dog or the fact that I understand him perfectly.",
        "My life is basically just one long Friends episode, except with less laughter and more existential dread.",
        "I'm not addicted to Netflix, we're just in a very committed relationship.",
        "Did you hear about the guy who lost his left arm and left leg in a car accident? He's all right now.",
        "I'm on a sushi diet. I eat everything in sight.",
        "I'm not sure what's happening, but I'm pretty sure I'm allergic to Mondays.",
        "My goal in life is to be so happy that when people ask me what's wrong, I'm genuinely confused."
    ]

    random_joke = random.choice(jokes)
    return random_joke